name: Deploy to Staging (FTP)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Installeer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

      - name: Installeer Node dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build

      - name: Upload naar STAGING server
        uses: samkirkland/ftp-deploy-action@v4.3.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./
          server-dir: public_addon/beheerstaging.jouw-gids.nl/